let token=localStorage.getItem("sl_token"), me=null, countries=[], sources=[];
const $=id=>document.getElementById(id);
function toast(t){$("toast").textContent=t;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2600)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:"Bearer "+token}:{})};if(opt.body&&typeof opt.body!=="string"){opt.headers["Content-Type"]="application/json";opt.body=JSON.stringify(opt.body)}const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Something went wrong");return d}
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");window.scrollTo({top:0,behavior:"smooth"});if(id==="universities")loadUniversities();if(id==="scholarships")loadSources();if(id==="dashboard")loadDashboard()}
function openModal(type){$("modal").classList.add("show");$("modalContent").innerHTML=type==="login"?`
<h2>Welcome back</h2><p class="meta">Log in to your ScholarLink account.</p><form class="form" onsubmit="login(event)">
<label>Email</label><input id="email" type="email" required><label>Password</label><input id="password" type="password" minlength="8" required><button class="btn">Log in</button><div class="notice">School administrators can use the same login. Admin access is permission-based.</div></form>`
:`
<h2>Create student account</h2><p class="meta">Your profile helps us personalize university matches.</p><form class="form" onsubmit="register(event)">
<label>Name</label><input id="rname" required><label>Email</label><input id="remail" type="email" required><label>Password</label><input id="rpass" type="password" minlength="8" required><button class="btn">Create account</button></form>`}
function closeModal(){$("modal").classList.remove("show")}
async function register(e){e.preventDefault();try{await api("/api/register",{method:"POST",body:{name:$("rname").value,email:$("remail").value,password:$("rpass").value}});toast("Account created. Please log in.");closeModal();openModal("login")}catch(x){toast(x.message)}}
async function login(e){e.preventDefault();try{const d=await api("/api/login",{method:"POST",body:{email:$("email").value,password:$("password").value}});token=d.token;me=d.user;localStorage.setItem("sl_token",token);closeModal();updateAuth();toast("Logged in successfully.");show("dashboard")}catch(x){toast(x.message)}}
function logout(){token=null;me=null;localStorage.removeItem("sl_token");updateAuth();show("home");toast("Logged out")}
function updateAuth(){ $("authButtons").innerHTML=token?`<button class="btn ghost" onclick="logout()">Log out</button><button class="btn" onclick="show('dashboard')">My dashboard</button>`:`<button class="btn ghost" onclick="openModal('login')">Login</button><button class="btn" onclick="openModal('register')">Register</button>`}
async function init(){countries=await fetch("/api/countries").then(r=>r.json());sources=await fetch("/api/scholarship-sources").then(r=>r.json());fillCountries();renderCountries();loadSources();if(token){try{const d=await api("/api/me");me=d.user}catch(e){token=null;localStorage.removeItem("sl_token")}}updateAuth()}
function fillCountries(){["homeCountry","uCountry"].forEach(id=>{const s=$(id);countries.forEach(c=>{const o=document.createElement("option");o.value=c[0];o.textContent=c[0];s.appendChild(o)})})}
function flag(country){const m={"Germany":"🇩🇪","United Kingdom":"🇬🇧","United States":"🇺🇸","Canada":"🇨🇦","Australia":"🇦🇺","Türkiye":"🇹🇷","Malaysia":"🇲🇾","China":"🇨🇳","Japan":"🇯🇵","South Korea":"🇰🇷","Finland":"🇫🇮","Sweden":"🇸🇪","France":"🇫🇷","Italy":"🇮🇹","Netherlands":"🇳🇱","Hungary":"🇭🇺","Poland":"🇵🇱","Czech Republic":"🇨🇿","Ireland":"🇮🇪","New Zealand":"🇳🇿","Spain":"🇪🇸","Portugal":"🇵🇹","Austria":"🇦🇹","Belgium":"🇧🇪","Denmark":"🇩🇰","Norway":"🇳🇴","Switzerland":"🇨🇭","UAE":"🇦🇪","Saudi Arabia":"🇸🇦","Qatar":"🇶🇦"};return m[country]||"🌍"}
function renderCountries(){const picks=countries.slice(0,10);$("countryCards").innerHTML=picks.map(c=>`<div class="country" onclick="$('uCountry').value='${c[0]}';show('universities');loadUniversities()"><div class="flag">${flag(c[0])}</div><b>${c[0]}</b><span>Universities & study sources</span></div>`).join("")}
async function loadUniversities(){const q=encodeURIComponent($("uQ")?.value||"");const c=encodeURIComponent($("uCountry")?.value||"");const l=encodeURIComponent($("uLevel")?.value||"");const data=await api(`/api/universities?q=${q}&country=${c}&level=${l}`);$("universityGrid").innerHTML=data.map(u=>`<article class="uni"><div class="flag">${flag(u.country)}</div><h3>${u.name}</h3><div class="meta">${u.country} · ${u.levels.join(", ")}</div><div class="tags">${u.fields.map(f=>`<span class="tag">${f}</span>`).join("")}</div><a class="cardBtn" href="${u.officialUrl}" target="_blank" rel="noopener">Official university site ↗</a></article>`).join("")||`<div class="notice">No universities matched these filters.</div>`}
function loadSources(){if(!$("sourceGrid"))return;$("sourceGrid").innerHTML=sources.map(s=>`<article class="source"><div class="flag">${flag(s.country)}</div><h3>${s.name}</h3><div class="meta">${s.country}</div><p class="meta">Verify current scholarship names, deadlines and eligibility on the official portal.</p><a class="cardBtn" href="${s.url}" target="_blank" rel="noopener">Open official source ↗</a></article>`).join("")}
async function homeSearch(){if(!token){openModal("register");toast("Create a student account to get personalized matches.");return}show("dashboard")}
async function loadDashboard(){if(!token){$("dashIntro").textContent="Log in to create your student profile.";$("dashContent").innerHTML=`<div class="notice">Create an account or log in to start your personalized university search.</div>`;return}
if(!me){try{me=(await api("/api/me")).user}catch(e){return}}
const p=await api("/api/profile");$("dashIntro").textContent=`Welcome, ${me.name}. Complete your profile and get matches.`;
$("dashContent").innerHTML=`<div class="adminBox" style="background:#fff;color:var(--ink);border:1px solid var(--line)"><h2>Student profile</h2><form class="form" onsubmit="saveProfile(event)">
<div style="display:grid;grid-template-columns:repeat(2,1fr);gap:10px"><input id="pfname" placeholder="Full name" value="${p?.fullName||me.name}" required><input id="phone" placeholder="Phone number" value="${p?.phone||''}" required><input id="city" placeholder="City" value="${p?.city||''}"><input id="education" placeholder="Current education" value="${p?.education||''}"><input id="marks" type="number" min="0" max="100" placeholder="Marks / percentage" value="${p?.marks||''}"><input id="field" placeholder="Field of study e.g. Computer Science" value="${p?.field||''}"><select id="studyLevel"><option value="">Study level</option>${["High School","Bachelor","Master","Doctorate"].map(x=>`<option ${p?.studyLevel===x?"selected":""}>${x}</option>`).join("")}</select><input id="budget" placeholder="Budget e.g. Full scholarship" value="${p?.budget||''}"></div>
<label>Preferred countries (Ctrl/Cmd + click for multiple)</label><select id="preferredCountries" multiple size="6">${countries.map(c=>`<option ${p?.preferredCountries?.includes(c[0])?"selected":""}>${c[0]}</option>`).join("")}</select>
<button class="btn">Save profile & find matches</button></form></div><div id="matches"></div>`;
if(p)showMatches();else $("matches").innerHTML=`<div class="notice">Fill your profile to generate your first matches.</div>`;
if(me.role==="admin") renderAdmin();
}
async function saveProfile(e){e.preventDefault();const selected=[...$("preferredCountries").selectedOptions].map(o=>o.value);try{await api("/api/profile",{method:"POST",body:{fullName:$("pfname").value,phone:$("phone").value,city:$("city").value,education:$("education").value,marks:$("marks").value,field:$("field").value,studyLevel:$("studyLevel").value,budget:$("budget").value,preferredCountries:selected}});toast("Profile saved.");showMatches()}catch(x){toast(x.message)}}
async function showMatches(){const d=await api("/api/matches");$("matches").innerHTML=`<div class="sectionHead"><div><span class="eyebrow">Personalized</span><h2>Best university matches</h2></div></div><div class="grid">${d.universities.map(u=>`<article class="match"><span class="score">${u.matchScore}% match</span><div class="flag">${flag(u.country)}</div><h3>${u.name}</h3><div class="meta">${u.country} · ${u.levels.join(", ")}</div><div class="tags">${u.fields.slice(0,4).map(f=>`<span class="tag">${f}</span>`).join("")}</div><a class="cardBtn" target="_blank" rel="noopener" href="${u.officialUrl}">Official university site ↗</a></article>`).join("")||`<div class="notice">No matches yet. Add a field, study level and preferred countries.</div>`}</div><h2 style="margin-top:35px">Scholarship & study portals</h2><div class="grid">${d.sources.map(s=>`<article class="source"><div class="flag">${flag(s.country)}</div><h3>${s.name}</h3><div class="meta">${s.country}</div><a class="cardBtn" target="_blank" rel="noopener" href="${s.url}">Official source ↗</a></article>`).join("")}</div>`;
}
async function renderAdmin(){const students=await api("/api/admin/students");const el=document.createElement("div");el.innerHTML=`<div class="adminBox"><h2>🏫 School Admin — Student management</h2><p style="color:#b8cddd">Add your school students here. Phone numbers and profile details stay inside the authenticated dashboard.</p><form class="adminForm" onsubmit="adminAdd(event)"><input id="afn" placeholder="Student full name" required><input id="aemail" type="email" placeholder="Student email" required><input id="aphone" placeholder="Phone number" required><input id="acity" placeholder="City"><input id="aedu" placeholder="Education"><input id="amarks" placeholder="Marks %"><input id="afield" placeholder="Field"><select id="alevel"><option value="">Study level</option><option>Bachelor</option><option>Master</option><option>Doctorate</option><option>High School</option></select><button class="btn">Add / update student</button></form></div><div class="tableWrap"><table class="table"><thead><tr><th>Student</th><th>Email</th><th>Phone</th><th>Education</th><th>Field</th><th></th></tr></thead><tbody>${students.map(s=>`<tr><td>${s.fullName||s.user?.name||"-"}</td><td>${s.user?.email||"-"}</td><td>${s.phone||"-"}</td><td>${s.education||"-"}</td><td>${s.field||"-"}</td><td><button class="danger" onclick="deleteStudent('${s.id}')">Delete</button></td></tr>`).join("")}</tbody></table></div>`;$("dashContent").appendChild(el)}
async function adminAdd(e){e.preventDefault();try{await api("/api/admin/students",{method:"POST",body:{fullName:$("afn").value,email:$("aemail").value,phone:$("aphone").value,city:$("acity").value,education:$("aedu").value,marks:$("amarks").value,field:$("afield").value,studyLevel:$("alevel").value}});toast("Student saved.");loadDashboard()}catch(x){toast(x.message)}}
async function deleteStudent(id){if(!confirm("Delete this student profile?"))return;try{await api("/api/admin/students/"+id,{method:"DELETE"});toast("Student deleted.");loadDashboard()}catch(x){toast(x.message)}}
init();